export const SITE_NAME = 'Maqola';

export const UZ = {
  doctorReviewed: 'Shifokor tomonidan tekshirilgan',
  allArticlesReviewed: 'Barcha maqolalar shifokor tomonidan tekshirilgan',
  lastUpdated: 'Oxirgi yangilanish',
  readTime: "O'qish vaqti",
  trustAndEditorial: 'Ishonch va tahririyat standartlari',
  reportError: 'Xato haqida xabar berish',
  medicalWarning: 'Tibbiy ogohlantirish',
  tableOfContents: 'Mazmuni',
  sources: 'Manbalar',
  viewProfile: "Profilni ko'rish",
  readMore: "Ko'proq o'qish",
  subscribe: "Obuna bo'lish",
  search: 'Qidiruv',
  searchPlaceholder: 'Kasallik, dori yoki mavzu qidiring',
  categories: 'Kategoriyalar',
  home: 'Bosh sahifa',
  clearFilters: 'Tozalash',
  clearSearch: 'Tozalash',
  closeSearch: 'Yopish',
  applyFilters: "Qo'llash",
  filters: 'Filtrlar',
  articles: 'maqola',
  minutes: 'daqiqa',
  results: 'natija',
  noResults: 'Hech narsa topilmadi',
  noResultsDesc: "Boshqa kalit so'zlar bilan qidirib ko'ring yoki kategoriyalarni ko'rib chiqing.",
  loadMore: "Ko'proq yuklash",
  previousPage: 'Oldingi sahifa',
  nextPage: 'Keyingi sahifa',
  pagination: 'Sahifalash',
  breadcrumbLabel: "Yo'l",
  emergencyCall: "103 raqamiga qo'ng'iroq qiling",
  emergencyHeading: 'Shoshilinch tibbiy yordam',
  warningHeading: 'Ogohlantirish',
  retry: 'Qayta urinish',
  errorTitle: 'Xatolik yuz berdi',
  errorDescription: "Ma'lumotlarni yuklashda xatolik yuz berdi. Iltimos, qayta urinib ko'ring.",
  disclaimer: "Bu platforma ta'lim maqsadida yaratilgan — shifokor tashxisi o'rnini bosmaydi. Aniq tashxisni faqat shifokor qo'yishi mumkin.",
  heroTitle: "Sog'ligingiz haqida ishonchli va tushunarli ma'lumot",
  heroSubtitle: "Shifokorlar tomonidan tekshirilgan, o'zbek tilidagi tibbiy maqolalar",
  subscribeSuccess: "Muvaffaqiyatli obuna bo'ldingiz!",
  emailError: "Email manzilni to'g'ri kiriting",
  aboutPlatform: 'Platforma haqida',
  legalLinks: 'Huquqiy',
  companyLinks: 'Kompaniya',
  privacyPolicy: 'Maxfiylik siyosati',
  termsOfUse: "Foydalanish shartlari",
  aboutUs: 'Biz haqimizda',
  contactUs: "Bog'lanish",
  reviewedBy: 'Tekshirgan',
  ourDoctors: 'Shifokorlarimiz',
  recentArticles: "So'nggi maqolalar",
  specializations: 'Mutaxassislik sohalari',
  education: "Ta'lim",
  loading: 'Yuklanmoqda...',
  briefSummary: 'Qisqacha xulosa',
  wasArticleHelpful: "Bu maqola foydali bo'ldimi?",
  yes: 'Ha',
  no: "Yo'q",
  thankYouFeedback: "Fikringiz uchun rahmat!",
  relatedArticles: "Sizga qiziq bo'lishi mumkin",
  authorAndReviewer: 'Muallif va tekshiruvchi',
  image: 'Rasm',
} as const;

export const NAV_ITEMS = [
  { label: UZ.home, href: '/' },
  { label: UZ.categories, href: '/kategoriya/yurak-qon-tomir' },
  { label: UZ.trustAndEditorial, href: '/ishonch' },
] as const;
